package com.evolutiondso.androiddoctor

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.time.Instant
import kotlin.KotlinVersion

abstract class AndroidDoctorCollectTask : DefaultTask() {

    @get:OutputFile
    abstract val reportFile: RegularFileProperty

    init {
        group = "verification"
        description = "Collect AndroidDoctor diagnostics (writes a basic report.json)."
    }

    @TaskAction
    fun run() {
        val file = reportFile.get().asFile
        file.parentFile.mkdirs()

        // Basic deterministic fields
        val now = Instant.now().toString()
        val projectName = project.name
        val projectPath = project.path
        val gradleVersion = project.gradle.gradleVersion
        val kotlinStdlibVersion = KotlinVersion.CURRENT.toString()
        val pluginVersion = project.version.toString()

        // ✅ Check 1: Android plugin detection
        val isAndroidApplication = project.plugins.hasPlugin("com.android.application")
        val isAndroidLibrary = project.plugins.hasPlugin("com.android.library")
        val isAndroidProject = isAndroidApplication || isAndroidLibrary

        // ✅ Check 2: kapt usage detection (very basic for now)
        val hasKaptPlugin =
            project.plugins.hasPlugin("org.jetbrains.kotlin.kapt") ||
                    project.plugins.hasPlugin("kotlin-kapt")

        val hasKaptConfiguration =
            project.configurations.names.any { name ->
                name.startsWith("kapt", ignoreCase = true)
            }

        val usesKapt = hasKaptPlugin || hasKaptConfiguration

        // ✅ Plugins summary (known plugin IDs)
        val knownPluginIds = listOf(
            "com.android.application",
            "com.android.library",
            "org.jetbrains.kotlin.android",
            "org.jetbrains.kotlin.jvm",
            "org.jetbrains.kotlin.plugin.serialization",
            "org.jetbrains.kotlin.kapt",
            "kotlin-kapt",
            "dagger.hilt.android.plugin",
            "com.google.dagger.hilt.android"
        )

        val appliedKnownPluginIds = knownPluginIds.filter { id ->
            project.plugins.hasPlugin(id)
        }

        val appliedKnownPluginsJson = appliedKnownPluginIds.joinToString(separator = ",") { id ->
            "\"$id\""
        }

        val json = """
            {
              "schemaVersion": 1,
              "generatedAt": "$now",
              "project": {
                "name": "$projectName",
                "path": "$projectPath"
              },
              "tooling": {
                "gradleVersion": "$gradleVersion",
                "kotlinStdlibVersion": "$kotlinStdlibVersion",
                "androidDoctorPluginVersion": "$pluginVersion"
              },
              "status": "skeleton",
              "checks": {
                "isAndroidApplication": $isAndroidApplication,
                "isAndroidLibrary": $isAndroidLibrary,
                "isAndroidProject": $isAndroidProject,
                "usesKapt": $usesKapt
              },
              "plugins": {
                "appliedKnownPluginIds": [ $appliedKnownPluginsJson ]
              },
              "notes": [
                "This report is generated by the AndroidDoctor Gradle plugin skeleton.",
                "Fields and structure will evolve; do not rely on this format yet."
              ]
            }
        """.trimIndent()

        file.writeText(json)

        logger.lifecycle("AndroidDoctor: report written to ${file.absolutePath}")
    }
}
