package com.evolutiondso.androiddoctor

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.time.Instant
import kotlin.KotlinVersion

abstract class AndroidDoctorCollectTask : DefaultTask() {

    @get:OutputFile
    abstract val reportFile: RegularFileProperty

    init {
        group = "verification"
        description = "Collect AndroidDoctor diagnostics (skeleton, writes a basic report.json)."
    }

    @TaskAction
    fun run() {
        val file = reportFile.get().asFile
        file.parentFile.mkdirs()

        // Basic deterministic fields
        val now = Instant.now().toString()
        val projectName = project.name
        val projectPath = project.path
        val gradleVersion = project.gradle.gradleVersion
        val kotlinStdlibVersion = KotlinVersion.CURRENT.toString()
        val pluginVersion = project.version.toString()

        val json = """
            {
              "schemaVersion": 1,
              "generatedAt": "$now",
              "project": {
                "name": "$projectName",
                "path": "$projectPath"
              },
              "tooling": {
                "gradleVersion": "$gradleVersion",
                "kotlinStdlibVersion": "$kotlinStdlibVersion",
                "androidDoctorPluginVersion": "$pluginVersion"
              },
              "status": "skeleton",
              "notes": [
                "This report is generated by the AndroidDoctor Gradle plugin skeleton.",
                "Fields and structure will evolve; do not rely on this format yet."
              ]
            }
        """.trimIndent()

        file.writeText(json)

        logger.lifecycle("AndroidDoctor: report written to ${file.absolutePath}")
    }
}
